version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    container_name: gocart_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gocart
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - "5432:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
  app:
    container_name: gocart_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/gocart?sslmode=disable
      - JWT_SECRET=vTPd2FOoRIMjmmWRpLjmXTq89UI8gncY

volumes:
  db_storage: