// Code generated by mockery v2.36.0. DO NOT EDIT.

package account

import (
	models "go-cart/pkg/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// mockAccountRepositoryImpl is an autogenerated mock type for the accountRepository type
type mockAccountRepositoryImpl struct {
	mock.Mock
}

// existsByEmail provides a mock function with given fields: tx, email
func (_m *mockAccountRepositoryImpl) existsByEmail(tx *gorm.DB, email string) error {
	ret := _m.Called(tx, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(tx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// save provides a mock function with given fields: tx, user
func (_m *mockAccountRepositoryImpl) save(tx *gorm.DB, user models.User) error {
	ret := _m.Called(tx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, models.User) error); ok {
		r0 = rf(tx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockAccountRepositoryImpl creates a new instance of mockAccountRepositoryImpl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAccountRepositoryImpl(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAccountRepositoryImpl {
	mock := &mockAccountRepositoryImpl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
